// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dashboard_weather128x128

#ifndef _DASHBOARD_WEATHER128X128_UI_H
#define _DASHBOARD_WEATHER128X128_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1299355463);    // assets/3-removebg-preview.png
LV_IMG_DECLARE(ui_img_384279421);    // assets/1-removebg-preview.png
LV_IMG_DECLARE(ui_img_1658401886);    // assets/2-removebg-preview.png
LV_IMG_DECLARE(ui_img_1731705873);    // assets/5-removebg-preview.png
LV_IMG_DECLARE(ui_img_1226051476);    // assets/4-removebg-preview.png
LV_IMG_DECLARE(ui_img_310975434);    // assets/6-removebg-preview.png
LV_IMG_DECLARE(ui_img_tempiconor20x20_png);    // assets/tempiconor20x20.png
LV_IMG_DECLARE(ui_img_windicon20x20_png);    // assets/windicon20x20.png
LV_IMG_DECLARE(ui_img_humidiconor20x20_png);    // assets/humidiconor20x20.png
LV_IMG_DECLARE(ui_img_logo20x20_png);    // assets/logo20x20.png

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
