// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dashboard_weather128x128

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_Screen1_screen_relocalize(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_rain;
extern lv_obj_t * ui_cloudy;
extern lv_obj_t * ui_clearsky;
extern lv_obj_t * ui_thunderstorm;
extern lv_obj_t * ui_storm;
extern lv_obj_t * ui_night;
extern lv_obj_t * ui_timevalue1;
extern lv_obj_t * ui_dayvalue;
extern lv_obj_t * ui_monthvalue;
extern lv_obj_t * ui_mapvalue;
extern lv_obj_t * ui_tempicon;
extern lv_obj_t * ui_tempvalue;
extern lv_obj_t * ui_windicon;
extern lv_obj_t * ui_humidicon;
extern lv_obj_t * ui_humdivalue;
extern lv_obj_t * ui_windvalue;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_cloudsvalue;
extern lv_obj_t * ui_Image6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

