// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dashboard_weather128x128

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_rain = NULL;
lv_obj_t * ui_cloudy = NULL;
lv_obj_t * ui_clearsky = NULL;
lv_obj_t * ui_thunderstorm = NULL;
lv_obj_t * ui_storm = NULL;
lv_obj_t * ui_night = NULL;
lv_obj_t * ui_timevalue1 = NULL;
lv_obj_t * ui_dayvalue = NULL;
lv_obj_t * ui_monthvalue = NULL;
lv_obj_t * ui_mapvalue = NULL;
lv_obj_t * ui_tempicon = NULL;
lv_obj_t * ui_tempvalue = NULL;
lv_obj_t * ui_windicon = NULL;
lv_obj_t * ui_humidicon = NULL;
lv_obj_t * ui_humdivalue = NULL;
lv_obj_t * ui_windvalue = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_weather = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_cloudsvalue = NULL;
lv_obj_t * ui_Image6 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Screen1, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_Screen1_screen_destroy);

    ui_rain = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_rain, &ui_img_1299355463);
    lv_obj_set_width(ui_rain, 58);
    lv_obj_set_height(ui_rain, 55);
    lv_obj_set_x(ui_rain, -60);
    lv_obj_set_y(ui_rain, 19);
    lv_obj_set_align(ui_rain, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_rain, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cloudy = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_cloudy, &ui_img_384279421);
    lv_obj_set_width(ui_cloudy, 58);
    lv_obj_set_height(ui_cloudy, 55);
    lv_obj_set_x(ui_cloudy, -60);
    lv_obj_set_y(ui_cloudy, 19);
    lv_obj_set_align(ui_cloudy, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_cloudy, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cloudy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clearsky = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_clearsky, &ui_img_1658401886);
    lv_obj_set_width(ui_clearsky, 58);
    lv_obj_set_height(ui_clearsky, 55);
    lv_obj_set_x(ui_clearsky, -60);
    lv_obj_set_y(ui_clearsky, 22);
    lv_obj_set_align(ui_clearsky, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_clearsky, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_clearsky, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_thunderstorm = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_thunderstorm, &ui_img_1731705873);
    lv_obj_set_width(ui_thunderstorm, 56);
    lv_obj_set_height(ui_thunderstorm, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_x(ui_thunderstorm, -60);
    lv_obj_set_y(ui_thunderstorm, 23);
    lv_obj_set_align(ui_thunderstorm, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_thunderstorm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_thunderstorm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_storm = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_storm, &ui_img_1226051476);
    lv_obj_set_width(ui_storm, 55);
    lv_obj_set_height(ui_storm, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_x(ui_storm, -60);
    lv_obj_set_y(ui_storm, 23);
    lv_obj_set_align(ui_storm, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_storm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_storm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_night = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_night, &ui_img_310975434);
    lv_obj_set_width(ui_night, 64);
    lv_obj_set_height(ui_night, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_x(ui_night, -60);
    lv_obj_set_y(ui_night, 16);
    lv_obj_set_align(ui_night, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_night, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_night, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timevalue1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timevalue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timevalue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timevalue1, 45);
    lv_obj_set_y(ui_timevalue1, -31);
    lv_obj_set_align(ui_timevalue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timevalue1, "11:30");
    lv_obj_set_style_text_color(ui_timevalue1, lv_color_hex(0xFFF80F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timevalue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timevalue1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_dayvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dayvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dayvalue, 37);
    lv_obj_set_y(ui_dayvalue, -17);
    lv_obj_set_align(ui_dayvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dayvalue, "18 JUN");
    lv_obj_set_style_text_color(ui_dayvalue, lv_color_hex(0x276CA3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dayvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dayvalue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monthvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_monthvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_monthvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_monthvalue, 46);
    lv_obj_set_y(ui_monthvalue, -3);
    lv_obj_set_align(ui_monthvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_monthvalue, "Thu");
    lv_obj_set_style_text_font(ui_monthvalue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mapvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_mapvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mapvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mapvalue, 12);
    lv_obj_set_y(ui_mapvalue, 6);
    lv_obj_set_align(ui_mapvalue, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_mapvalue, "Ho Chi Minh");
    lv_obj_set_style_text_color(ui_mapvalue, lv_color_hex(0x276CA3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mapvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mapvalue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempicon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_tempicon, &ui_img_tempiconor20x20_png);
    lv_obj_set_width(ui_tempicon, 20);
    lv_obj_set_height(ui_tempicon, 20);
    lv_obj_set_x(ui_tempicon, -40);
    lv_obj_set_y(ui_tempicon, 34);
    lv_obj_set_align(ui_tempicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tempicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempvalue, -26);
    lv_obj_set_y(ui_tempvalue, 32);
    lv_obj_set_align(ui_tempvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempvalue, "20");
    lv_obj_set_style_text_font(ui_tempvalue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_windicon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_windicon, &ui_img_windicon20x20_png);
    lv_obj_set_width(ui_windicon, 20);
    lv_obj_set_height(ui_windicon, 20);
    lv_obj_set_x(ui_windicon, -31);
    lv_obj_set_y(ui_windicon, 49);
    lv_obj_set_align(ui_windicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_windicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_windicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humidicon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_humidicon, &ui_img_humidiconor20x20_png);
    lv_obj_set_width(ui_humidicon, 20);
    lv_obj_set_height(ui_humidicon, 20);
    lv_obj_set_x(ui_humidicon, 18);
    lv_obj_set_y(ui_humidicon, 34);
    lv_obj_set_align(ui_humidicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humidicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humidicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humdivalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_humdivalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humdivalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humdivalue, 36);
    lv_obj_set_y(ui_humdivalue, 32);
    lv_obj_set_align(ui_humdivalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humdivalue, "74%");
    lv_obj_set_style_text_font(ui_humdivalue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_windvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_windvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_windvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_windvalue, -9);
    lv_obj_set_y(ui_windvalue, 50);
    lv_obj_set_align(ui_windvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_windvalue, "0.0");
    lv_obj_set_style_text_font(ui_windvalue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 10);
    lv_obj_set_y(ui_Label10, 50);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "m/s|");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather, 2);
    lv_obj_set_y(ui_weather, 15);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather, "Overcasclouds");
    lv_obj_set_style_text_font(ui_weather, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 49);
    lv_obj_set_height(ui_Container1, 47);
    lv_obj_set_x(ui_Container1, -3);
    lv_obj_set_y(ui_Container1, 24);
    lv_obj_set_align(ui_Container1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0xFFF80F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 120);
    lv_obj_set_height(ui_Container2, 39);
    lv_obj_set_x(ui_Container2, 1);
    lv_obj_set_y(ui_Container2, -2);
    lv_obj_set_align(ui_Container2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0xFFFF88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -11);
    lv_obj_set_y(ui_Label6, 32);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "°C");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cloudsvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_cloudsvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cloudsvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cloudsvalue, 33);
    lv_obj_set_y(ui_cloudsvalue, 50);
    lv_obj_set_align(ui_cloudsvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cloudsvalue, "87%");
    lv_obj_set_style_text_font(ui_cloudsvalue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image6, &ui_img_logo20x20_png);
    lv_obj_set_width(ui_Image6, 21);
    lv_obj_set_height(ui_Image6, 21);
    lv_obj_set_x(ui_Image6, -47);
    lv_obj_set_y(ui_Image6, 6);
    lv_obj_set_align(ui_Image6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image6, 1);
    lv_obj_set_style_radius(ui_Image6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Image6, lv_color_hex(0x276CA3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image6, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Image6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_rain = NULL;
    ui_cloudy = NULL;
    ui_clearsky = NULL;
    ui_thunderstorm = NULL;
    ui_storm = NULL;
    ui_night = NULL;
    ui_timevalue1 = NULL;
    ui_dayvalue = NULL;
    ui_monthvalue = NULL;
    ui_mapvalue = NULL;
    ui_tempicon = NULL;
    ui_tempvalue = NULL;
    ui_windicon = NULL;
    ui_humidicon = NULL;
    ui_humdivalue = NULL;
    ui_windvalue = NULL;
    ui_Label10 = NULL;
    ui_weather = NULL;
    ui_Container1 = NULL;
    ui_Container2 = NULL;
    ui_Label6 = NULL;
    ui_cloudsvalue = NULL;
    ui_Image6 = NULL;

}

void ui_Screen1_screen_relocalize(void)
{
    // label widgets on screen

}
